services:
  # Main web service
  - type: web
    name: portfolio
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString

# PostgreSQL database
databases:
  - name: portfolio-db
    plan: free
    databaseName: portfolio
    user: portfolio_user